# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=12)),
            ],
        ),
    ]
