# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaWorkApi', '0005_teammembers_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nzme', models.CharField(max_length=10)),
            ],
        ),
    ]
