# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaWorkApi', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='role',
        ),
    ]
